TICKERS = [
    'ADANIENT.NS', 'ADANIPORTS.NS', 'APOLLOHOSP.NS', 'ASIANPAINT.NS', 'AXISBANK.NS',
    'BAJAJ-AUTO.NS', 'BAJFINANCE.NS', 'BAJAJFINSV.NS', 'BPCL.NS', 'BHARTIARTL.NS',
    'BRITANNIA.NS', 'CIPLA.NS', 'COALINDIA.NS', 'DIVISLAB.NS', 'DRREDDY.NS',
    'EICHERMOT.NS', 'GRASIM.NS', 'HCLTECH.NS', 'HDFCBANK.NS', 'HDFCLIFE.NS',
    'HEROMOTOCO.NS', 'HINDALCO.NS', 'HINDUNILVR.NS', 'ICICIBANK.NS', 'ITC.NS',
    'INDUSINDBK.NS', 'INFY.NS', 'JSWSTEEL.NS', 'KOTAKBANK.NS', 'LTIM.NS', 'LT.NS',
    'M&M.NS', 'MARUTI.NS', 'NTPC.NS', 'NESTLEIND.NS', 'ONGC.NS', 'POWERGRID.NS',
    'RELIANCE.NS', 'SBILIFE.NS', 'SBIN.NS', 'SUNPHARMA.NS', 'TCS.NS', 'TATACONSUM.NS',
    'TATAMOTORS.NS', 'TATASTEEL.NS', 'TECHM.NS', 'TITAN.NS', 'ULTRACEMCO.NS',
    'UPL.NS', 'WIPRO.NS'
]
BENCHMARK_TICKER = '^NSEI'

START_DATE = '2015-01-01'
END_DATE = '2023-12-31'
TRAIN_TEST_SPLIT = 0.80

OUTPUT_DIR = 'project_data'
RAW_DATA_PATH = f'{OUTPUT_DIR}/stock_prices.csv'
BENCHMARK_PATH = f'{OUTPUT_DIR}/benchmark_data.csv'
TRAIN_DATA_PATH = f'{OUTPUT_DIR}/train_data_scaled.csv'
TEST_DATA_PATH = f'{OUTPUT_DIR}/test_data_scaled.csv'

MODEL_OUTPUT_DIR = 'training_outputs'
MODEL_PATH = f'{MODEL_OUTPUT_DIR}/ppo_portfolio_model.zip'
TENSORBOARD_LOG_DIR = f'{MODEL_OUTPUT_DIR}/logs/'
RESULTS_PATH = f'{MODEL_OUTPUT_DIR}/evaluation_results.csv'

WINDOW_LENGTH = 30
TRAINING_TIMESTEPS = 500000  
FEATURES_DIM = 128